version: '3.8'

services:
  user_service:
    image: deividgp/sigma-user-service:latest
    container_name: sigma-user-service
    ports:
      - "8081:8080"
    depends_on:
      - mongodb

  security_service:
    image: deividgp/sigma-security-service:latest
    container_name: sigma-security-service
    ports:
      - "8082:8080"
    depends_on:
      - mongodb

  server_service:
    image: deividgp/sigma-server-service:latest
    container_name: sigma-server-service
    ports:
      - "8083:8080"
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
